/* SPDX-License-Identifier: LGPL-2.1-or-later */
/* Copyright (C) 2026 Mark Liversedge */
/*
 * hm_fixtures.h — golden wire vectors, hand-computed from docs/specification.md.
 *
 * Every byte here was written by hand and every expected value below it was
 * computed by hand from the section named beside it.  That is the point: a
 * fixture generated by the same code it tests proves only that the code is
 * self-consistent.  These catch byte order, field offsets and scale selectors,
 * which is exactly the class of bug the specification warns is silent — §1's
 * table exists because byte order is NOT uniform across this protocol.
 */
#ifndef HM_FIXTURES_H
#define HM_FIXTURES_H

#include <stdint.h>

/* ------------------------------------------------------------------------ */
/* 0x90 stream frame, one record, config 0x7e (§6.3, §6.4)                   */
/*                                                                           */
/*   header  0x0123               = 291                                      */
/*   arm  q  0x4000,0,0,0         = (1, 0, 0, 0), |q| = 16384                */
/*        a  100, -200, 0         = (0.98, -1.96, 0) m/s²  @ 0.0098 per LSB  */
/*        g  800, 0, -1600        = (100, 0, -200) °/s     @ /8 (bit 6 set)  */
/*        t  0x1234               = 4660                                     */
/*   palm q  0x2D41,0x2D41,0,0    = (0.7071, 0.7071, 0, 0), |q| = 16384.0    */
/*        t  0x126F               = 4719  → skew = +59 ticks (§10.3)         */
/* ------------------------------------------------------------------------ */
static const uint8_t HM_FIX_FRAME_7E[47] = {
    0x90,
    0x01, 0x23,
    /* lower arm */
    0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x64, 0xFF, 0x38, 0x00, 0x00,
    0x03, 0x20, 0x00, 0x00, 0xF9, 0xC0,
    0x12, 0x34,
    /* palm */
    0x2D, 0x41, 0x2D, 0x41, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x12, 0x6F
};

/* ------------------------------------------------------------------------ */
/* 0x7f legacy frame (§6.3.1) — 43 bytes, ONE record, NO header, NO ticks,   */
/* 21-byte blocks whose trailing byte read 00 in all 981 frames observed.    */
/* Gyro divisor is the nominal 16 here, so 800 → 50 °/s, not 100.            */
/* ------------------------------------------------------------------------ */
static const uint8_t HM_FIX_FRAME_LEGACY[43] = {
    0x7F,
    0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x64, 0xFF, 0x38, 0x00, 0x00,
    0x03, 0x20, 0x00, 0x00, 0xF9, 0xC0,
    0x00,
    0x2D, 0x41, 0x2D, 0x41, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00
};

/* 0x80 — versions (§5.2).  hw 4.1, protocol 4.0, firmware 4.8, product 0x14. */
static const uint8_t HM_FIX_VERSIONS[8] = {0x80, 0x04, 0x01, 0x04, 0x00, 0x04, 0x08, 0x14};

/* 0x81 — battery/status (§5.3).  100 %, then a u16be observed at 2226-2235
 * that is NOT millivolts and remains undecoded. */
static const uint8_t HM_FIX_STATUS[4] = {0x81, 0x64, 0x08, 0xB2}; /* 0x08B2 = 2226 */

/* 0x84 — sensor map (§5.4).  Two sensors: why every record carries two blocks. */
static const uint8_t HM_FIX_SENSOR_MAP[3] = {0x84, 0x02, 0x01};

/* 0x85 — MAC, 12 ASCII hex characters with no separators (§4). */
static const uint8_t HM_FIX_MAC[13] = {0x85, '0', '1', '2', '3', '4', '5',
                                       '6',  '7', '8', '9', 'A', 'B'};

/* 0x86 — serial, 9 ASCII bytes (§4). */
static const uint8_t HM_FIX_SERIAL[10] = {0x86, 'W', 'G', '3', '-', '0', '0', '0', '4', '2'};

/* 0xa1 — history bracket (§7.2).  02 = start (the acceptance test), 01 = end. */
static const uint8_t HM_FIX_HIST_START[2] = {0xA1, 0x02};
static const uint8_t HM_FIX_HIST_END[2]   = {0xA1, 0x01};

/* 0xd0 — the ONLY error the history command produces, across seven distinct
 * causes.  It says nothing about which (§7.2). */
static const uint8_t HM_FIX_DEVICE_ERROR[2] = {0xD0, 0x03};

/* 0xfb — button.  An edge HINT: one confirmed press produced none, another
 * produced two 187 ms apart (§9.4). */
static const uint8_t HM_FIX_BUTTON[2] = {0xFB, 0x01};

/* 0xa0 — start acknowledgement.  ⚠ The app ignores it and so must a client:
 * stream startup is keyed off the first 0x90 frame (§5.1). */
static const uint8_t HM_FIX_START_ACK[2] = {0xA0, 0x01};

/* 0x83 — stop acknowledgement (§4, §6.1). */
static const uint8_t HM_FIX_STOP_ACK[2] = {0x83, 0x01};

/* 0x94 — calibration result, 64 payload bytes, deliberately undecoded: the
 * device applies the transform itself (§8.2). */
static const uint8_t HM_FIX_CALIBRATION[65] = {
    0x94,
    0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E,
    0x1F, 0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D,
    0x2E, 0x2F, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A, 0x3B, 0x3C,
    0x3D, 0x3E, 0x3F, 0x40
};

/* ------------------------------------------------------------------------ */
/* The single-axis fixture api-request §2.2 asked for.                       */
/*                                                                           */
/* ⚠ It is the ONLY check that distinguishes q_palm ⊗ q_arm* from the        */
/* reverse.  The wrist angle is convention-blind, so a decode validated by    */
/* "the angle looks sensible" passes with the order reversed and every        */
/* decomposed component sign-flipped (§6.7).                                  */
/*                                                                           */
/*   q_arm  = 180° about y            = (0, 0, 1, 0)                          */
/*   q_palm = q_rel ⊗ q_arm           = (0, 0, cos30°, sin30°)                */
/*   correct  q_palm ⊗ q_arm*  = (cos30°, +sin30°, 0, 0)  → +60° about +x     */
/*   reversed q_arm* ⊗ q_palm  = (cos30°, −sin30°, 0, 0)  → 60° about −x      */
/*                                                                           */
/* Same angle, opposite sign.  Exactly as the specification describes.        */
/* ------------------------------------------------------------------------ */
#define HM_FIX_AXIS_ARM_Q  {0, 0, 16384, 0}       /* (0, 0, 1.0, 0)           */
#define HM_FIX_AXIS_PALM_Q {0, 0, 14189, 8192}    /* (0, 0, 0.86603, 0.5)     */
#define HM_FIX_AXIS_EXPECTED_ANGLE_DEG 60.0f
#define HM_FIX_AXIS_EXPECTED_REL_X     0.5f       /* ⚠ positive; reversed gives −0.5 */

#endif /* HM_FIXTURES_H */
